- id: '1604383268941'
  alias: Notify when smoke detected
  description: ''
  trigger:
  - type: smoke
    platform: device
    device_id: d4cd0c36dd3a19c9e5569b206439d88c
    entity_id: binary_sensor.unknown_type_0001_id_0003_smoke_alarm_smoke_detected
    domain: binary_sensor
  condition: []
  action:
  - service: notify.gmail
    data:
      title: Pandemicabin Alert
      message: Smoke Detected
  mode: single
- id: '1604383451997'
  alias: Notify when carbon monoxide detected
  description: ''
  trigger:
  - type: gas
    platform: device
    device_id: d4cd0c36dd3a19c9e5569b206439d88c
    entity_id: binary_sensor.unknown_type_0001_id_0003_carbon_monoxide_carbon_monoxide_detected
    domain: binary_sensor
  condition: []
  action:
  - service: notify.gmail
    data:
      title: Pandemicabin Alert
      message: Carbon monoxide detected
  mode: single
- id: '1605281259031'
  alias: Battery Low Alert
  description: ''
  mode: parallel
  trigger:
    - platform: numeric_state
      entity_id: 
        - sensor.lumi_lumi_weather_5aac8205_power
        - sensor.lumi_lumi_weather_64aa8205_power
        - sensor.samjin_multi_0e220d01_power
        - sensor.samjin_multi_cc1d0d01_power
        - sensor.samjin_multi_dd210d01_power
        - sensor.samjin_multi_fcd00d01_power
        - sensor.gc_tbz48_battery_powered_z_wave_thermostat_battery_level
        - sensor.unknown_type_0001_id_0003_battery_level
        - sensor.zse40_4_in_1_sensor_battery_level
        - sensor.lumi_lumi_sensor_magnet_aq2_e4a8a902_power
      below: 40
  action:
  - service: notify.persistent_notification
    data:
      title: Battery Low Alert
      message: '{{state_attr(trigger.entity_id, "friendly_name")}} is at {{trigger.to_state.state}}%'
- id: '1605406740002'
  alias: Notify on door window event
  trigger:
    - platform: state
      from: "off"
      to: "on"
      entity_id:
        - binary_sensor.samjin_multi_0e220d01_ias_zone
        - binary_sensor.samjin_multi_cc1d0d01_ias_zone
        - binary_sensor.samjin_multi_dd210d01_ias_zone
        - binary_sensor.samjin_multi_fcd00d01_ias_zone
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_e4a8a902_on_off
  condition:
    - condition: state
      entity_id: 
        - input_boolean.notify_on_door_window_events
      state: "on"
  action:
    - service: notify.gmail
      data_template:
        title: Pandemicabin Alert
        message: '{{state_attr(trigger.entity_id, "friendly_name")}} is open'
    - service: alarm_control_panel.alarm_trigger
      data:
        entity_id: alarm_control_panel.alarm
- id: "1605491801008"
  alias: Notify on motion house
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.zse40_4_in_1_sensor_home_security_motion_detected_2
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: 
        - input_boolean.notify_on_motion
      state: "on"
  action:
    - service: notify.gmail
      data_template:
        title: Pandemicabin Alert
        message: '{{state_attr(trigger.entity_id, "friendly_name")}} is open'
    - service: alarm_control_panel.alarm_trigger
      data:
        entity_id: alarm_control_panel.alarm
- id: "1605492586935"
  alias: Notify on motion garage
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.zse40_4_in_1_sensor_home_security_motion_detected
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id:
        - input_boolean.notify_on_motion_garage
      state: "on"
  action:
    - service: notify.gmail
      data_template:
        title: Pandemicabin Alert
        message: '{{state_attr(trigger.entity_id, "friendly_name")}} is open'
    - service: alarm_control_panel.alarm_trigger
      data:
        entity_id: alarm_control_panel.alarm
- id: "1605457574856"
  alias: Alarm turn on alerts
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
  action:
    - service: >-
        {% if trigger.to_state.state == 'disarmed' -%} 
          input_boolean.turn_off
        {%- else -%}
          input_boolean.turn_on
        {%- endif %}
      data:
        entity_id: >-
          {% if trigger.to_state.state == 'armed_home' -%}
            input_boolean.notify_on_door_window_events, input_boolean.notify_on_motion_garage
          {%- else -%}
            input_boolean.notify_on_door_window_events, input_boolean.notify_on_motion, input_boolean.notify_on_motion_garage
          {%- endif %}
- id: "1605533510025"
  alias: Alarm self arm home when disarmed
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.zse40_4_in_1_sensor_home_security_motion_detected_2
      from: "on"
      to: "off"
      for: 60
  condition:
    - condition: time
      after: "23:00:00"
      before: "04:00:00"
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: disarmed
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.alarm
- id: "1605537922330"
  alias: Alarm self disarm when armed home
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.samjin_multi_fcd00d01_ias_zone
        - binary_sensor.samjin_multi_0e220d01_ias_zone
      from: "off"
      to: "on"
  condition:
    - condition: time
      after: "05:00:00"
      before: "12:00:00"
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: template
      value_template: >-
        {{ 15 < (as_timestamp(utcnow()) - 
            as_timestamp(states.binary_sensor.zse40_4_in_1_sensor_home_security_motion_detected_2.last_changed)) }}
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.alarm
- id: '1606512448888'
  alias: Notify doors open too long
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.samjin_multi_0e220d01_ias_zone
        - binary_sensor.samjin_multi_fcd00d01_ias_zone
      from:  'off'
      to: 'on'
      for: 00:05:00
  condition:
    - condition: state
      entity_id:
        - input_boolean.guest_mode
      state: 'off'
  action:
    - service: tts.google_translate_say
      data:
        entity_id: media_player.living_room_speaker
        message: >-
          "The " {{state_attr(trigger.entity_id, "friendly_name")}} " was left open."
    - service: script.notify_conditional
      data:
        recipient: all
        title: 'Pandemicabin Alerts'
        message: >-
          "The " {{state_attr(trigger.entity_id, "friendly_name")}} " was left open."
