group:
  temperature_sensors_indoor:
    name: Indoor Temperature Sensors
    entities:
      - sensor.lumi_lumi_weather_64aa8205_temperature
      - sensor.4_in_1_sensor_air_temperature_2
      - sensor.samjin_multi_0e220d01_temperature
      - sensor.samjin_multi_cc1d0d01_temperature
      - sensor.samjin_multi_dd210d01_temperature
      - sensor.samjin_multi_fcd00d01_temperature
      - sensor.z_wave_plus_thermostat_air_temperature
  humidity_sensors_indoor:
    name: Indoor Humidity Sensors
    entities:
      - sensor.lumi_lumi_weather_64aa8205_humidity
      - sensor.4_in_1_sensor_humidity_2

template:
  - sensor:
    - unique_id: humidity_overall
      name: Overall Humidity
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {{
          ((
            states("sensor.lumi_lumi_weather_64aa8205_humidity")|float +
            states("sensor.4_in_1_sensor_humidity_2")|float
          ) / 2) | round(1)
        }}
    - unique_id: temperature_overall
      name: Overall Temperature
      unit_of_measurement: "°F"
      device_class: temperature
      state: >-
        {{ 
          ((
            states("sensor.lumi_lumi_weather_64aa8205_temperature")|float * 2 + 
            states("sensor.4_in_1_sensor_air_temperature_2")|float * 2 +
            states("sensor.samjin_multi_0e220d01_temperature")|float +
            states("sensor.samjin_multi_cc1d0d01_temperature")|float * 0.5 +
            states("sensor.samjin_multi_dd210d01_temperature")|float * 0.5 +
            states("sensor.samjin_multi_fcd00d01_temperature")|float  + 
            states("sensor.z_wave_plus_thermostat_air_temperature")|float * 3
          ) / 10) | round(1)
        }}
  - binary_sensor:
    - unique_id: thermostat_hvac_action_heating
      name: HVAC Heating
      state: "{{ state_attr('climate.z_wave_plus_thermostat')}}"

automation:
  - id: '1604357736956'
    alias: Alert when temperatures are low
    description: ''
    trigger:
    - type: temperature
      platform: device
      device_id: 780eb4a06d73cd665382dd2c0d921f7d
      entity_id: sensor.lumi_lumi_weather_5aac8205_temperature
      domain: sensor
      below: 35
      for:
        hours: 0
        minutes: 0
        seconds: 0
    - type: temperature
      platform: device
      device_id: cb2cb27897a4790cb66cbe22ee77ed15
      entity_id: sensor.lumi_lumi_weather_64aa8205_temperature
      domain: sensor
      below: 45
      for:
        hours: 0
        minutes: 0
        seconds: 0
    condition: []
    action:
    - service: script.notify_parents
      data:
        title: GetawAframe Alert
        message: '{{state_attr(trigger.entity_id, "friendly_name")}} is {{trigger.to_state.state}}°F'
        alert_level: Warn
    mode: single

  - id: '1604460928355'
    alias: Thermostat Automation Weekday 1
    description: Set heat based on a schedule
    trigger:
    - platform: time
      at: input_datetime.heat_weekday_1
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - alias: "Guest mode off"
      condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    action:
    - service: input_number.set_value
      data:
        value: '{{states.input_number.heat_setpoint_weekday_1.state}}'
      entity_id: input_number.heat_auto_setpoint
    mode: single

  - id: '1604461665066'
    alias: Thermostat Automation Weekday 2
    description: ''
    trigger:
    - platform: time
      at: input_datetime.heat_weekday_2
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - sun
    action:
    - service: input_number.set_value
      entity_id: input_number.heat_auto_setpoint
      data:
        value: '{{states.input_number.heat_setpoint_weekday_2.state}}'
    mode: single
  - id: '1604544737759'
    alias: Thermostat Automation Weekend 1
    description: ''
    trigger:
    - platform: time
      at: input_datetime.heat_weekend_1
    condition:
    - condition: time
      weekday:
      - sat
      - sun
    - alias: "Guest mode off"
      condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    action:
    - service: input_number.set_value
      data:
        value: '{{states.input_number.heat_setpoint_weekend_1.state}}'
      entity_id: input_number.heat_auto_setpoint
    mode: single

  - id: '1604544994545'
    alias: Thermostat Automation Weekend 2
    description: ''
    trigger:
    - platform: time
      at: input_datetime.heat_weekend_2
    condition:
    - condition: time
      weekday:
      - fri
      - sat
    - alias: "Guest mode off"
      condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    action:
    - service: input_number.set_value
      data:
        value: '{{states.input_number.heat_setpoint_weekend_2.state}}'
      entity_id: input_number.heat_auto_setpoint
    mode: single

  - id: '1604546145850'
    alias: Thermostat Update From Auto Setpoint
    description: Take the value sent to the Heat Auto Setpoint and push to thermostat
    trigger:
    - platform: state
      entity_id: input_number.heat_auto_setpoint
    - platform: state
      entity_id: input_boolean.thermostat_hold_temp
      from: 'on'
      to: 'off'
    condition:
    - condition: state
      entity_id: input_boolean.thermostat_hold_temp
      state: 'off'
    action:
      - alias: "choose alias (name)"
        choose:
          - conditions:
            - alias: "condition alias (name)"
              condition: state
              entity_id: input_boolean.guest_mode
              state: "on"
            sequence:
              - service: climate.set_temperature
                data:
                  temperature: '{{states("input_number.guest_heat_setpoint")}}'
                target:
                  entity_id: climate.z_wave_plus_thermostat
        default:
        - service: climate.set_temperature
          data:
            temperature: '{{states("input_number.heat_auto_setpoint")}}'
          entity_id: climate.z_wave_plus_thermostat
    mode: single

  - id: '1604803745717'
    alias: Thermostat set when away
    description: ''
    trigger:
    - platform: state
      entity_id: input_boolean.heat_away
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: climate.set_temperature
      data:
        temperature: '{{states.input_number.heat_setpoint_away.state}}'
      entity_id: climate.z_wave_plus_thermostat
    - service: input_boolean.turn_on
      data: {}
      entity_id: input_boolean.thermostat_hold_temp
    mode: single

  - id: '1604803985924'
    alias: Thermostat set when return
    description: ''
    trigger:
      - platform: state
        entity_id: input_boolean.heat_away
        from: 'on'
        to: 'off'
    condition: []
    action:
      - service: input_boolean.turn_off
        data: {}
        entity_id: input_boolean.thermostat_hold_temp
    mode: single

  - id: '1608690287161'
    alias: Thermostat set when armed away
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: armed_away
    condition:
      - condition: state
        entity_id: input_boolean.heat_away
        state: 'off'
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.thermostat_hold_temp
      - service: climate.set_temperature
        data:
          entity_id: climate.z_wave_plus_thermostat
          temperature: '{{states("input_number.heat_setpoint_short_away")}}'
