input_select:
  notify_level_michael:
    name: Notify Level Michael
    options:
      - Debug
      - Info
      - Warn
      - None
    icon: mdi:bell-ring

  notify_level_angela:
    name: Notify Level Angela
    options:
      - Debug
      - Info
      - Warn
      - None
    icon: mdi:bell-ring

notify:
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret gmail_recipient_2
    encryption: starttls
    username: !secret gmail_recipient_2
    password: !secret gmail_password
    recipient:
      - !secret gmail_recipient_1
      - !secret gmail_recipient_2
    sender_name: Pandemicabin
  - name: master_ha_notify
    platform: rest
    resource: http://100.119.81.44:8122/api/services/notify/notify
    method: POST_JSON
    headers:
      Authorization: !secret master_ha_header
    title_param_name: title
    message_param_name: message
  - name: master_ha_michael
    platform: rest
    resource: http://100.119.81.44:8122/api/services/notify/michael
    method: POST_JSON
    headers:
      Authorization: !secret master_ha_header
    title_param_name: title
    message_param_name: message
  - name: master_ha_angela
    platform: rest
    resource: http://100.119.81.44:8122/api/services/notify/angela
    method: POST_JSON
    headers:
      Authorization: !secret master_ha_header
    title_param_name: title
    message_param_name: message
  - name: master_ha_camille
    platform: rest
    resource: http://100.119.81.44:8122/api/services/notify/camille
    method: POST_JSON
    headers:
      Authorization: !secret master_ha_header
    title_param_name: title
    message_param_name: message
  - name: local_methods
    platform: group
    services:
      - service: gmail
      - service: huawei_lte

automation:
  - id: '1604383268941'
    alias: Notify when smoke detected
    description: ''
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_smoke_detected
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_smoke_detected_2
        from: "off"
        to: "on"
    condition: []
    action:
      - service: script.notify_conditional
        data:
          recipient: all
          title: Pandemicabin Alert
          message: Smoke Detected
    mode: single

  - id: '1604383451997'
    alias: Notify when carbon monoxide detected
    description: ''
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.zcombo_g_smoke_co_alarm_co_alarm_carbon_monoxide_detected
          - binary_sensor.zcombo_g_smoke_co_alarm_co_alarm_carbon_monoxide_detected_2
        from: "off"
        to: "on"
    condition: []
    action:
      - service: script.notify_conditional
        data:
          recipient: all
          title: Pandemicabin Alert
          message: Carbon monoxide detected
    mode: single
  
script:
  notify_conditional:
    alias: 'Notify based on availablity of notifiers'
    description: ''
    fields:
      recipient:
        description: 'Who to notify'
        example: '[all|michael|angela|camille]'
      title:
        description: 'Title of the notification'
        example: 'Message Title'
      message:
        description: 'Message of the notification'
        example: 'Message body'
    sequence:
      - service: homeassistant.update_entity
        entity_id: binary_sensor.master_ha_api
      - service: >-
          {%- if states("binary_sensor.master_ha_api") != "on" -%}
            notify.local_methods
          {%- elif recipient == "michael" -%}
            notify.mobile_app_kashyyyk
          {%- elif recipient == "angela" -%}
            notify.mobile_app_iphone_58
          {%- elif recipient == "camille" -%}
            notify.master_ha_camille
          {%- else -%}
            notify.notify
          {%- endif -%}
        data:
          title: "{{ title }}"
          message: "{{ message }}"

  notify_camille_with_sound:
    alias: "Notify Camille with sound"
    variables:
      volume: >
        {{ state_attr("media_player.living_room_speaker_2", "volume_level") }}
      currentlyPlaying: >
        {{ states.media_player.living_room_speaker_2 }}
    fields:
      message:
        description: Message to broadcast to speaker
        example: "Camille, time to wake up"
    sequence:
      - alias: "pause anything currently playing"
        service: media_player.media_stop
        target:
          entity_id: media_player.living_room_speaker_2
      - alias: "Raise volume on speakers"
        service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker_2
        data:
          volume_level: 0.5
      - alias: "Google TTS to camille's speakers"
        service: tts.google_translate_say
        target:
          entity_id:
            - media_player.living_room_speaker_2
        data:
          message: "{{ message }}"
      - alias: "Return volume on speakers"
        service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker_2
        data:
          volume_level: "{{ volume }}"

  notify_with_sound:
    alias: "Notify with sound"
    variables:
      volume: >
        {{ state_attr("media_player.living_room_speaker_2", "volume_level") }}
      currentlyPlaying: >
        {{ states.media_player.living_room_speaker_2 }}
    fields:
      message:
        description: Message to broadcast to speaker
        example: "The front door was left open"
    sequence:
      - alias: "pause anything currently playing"
        service: media_player.media_stop
        target:
          entity_id: media_player.living_room_speaker_2
      - alias: "Raise volume on speakers"
        service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker_2
        data:
          volume_level: 0.5
      - alias: "Google TTS to speakers"
        service: tts.google_translate_say
        target:
          entity_id:
            - media_player.living_room_speaker_2
        data:
          message: "{{ message }}"
      - alias: "Return volume on speakers"
        service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker_2
        data:
          volume_level: "{{ volume }}"

  notify_michael:
    alias: "Notifications for Michael"
    fields:
      title:
        description: Notification Title
        example: GetawAframe Alert
      message:
        description: Notification Message Body
        example: Motion on front camera
      alert_level: 
        description: 'Level of alertness'
        example: '[Debug|Info|Warn]'
        default: Warn
    variables:
      set_alert_level: '{{ states("input_select.notify_level_michael")}}'
      alert_group: >-
        {% if alert_level == 'Debug' %}
          {{ ('Debug') }}
        {% elif alert_level == 'Info' %}
          {{ ('Debug', 'Info') }}
        {% else %}
          {{ ('Debug', 'Info', 'Warn') }}
        {% endif %}
    sequence:
      - alias: "Check if we should send notification"
        choose:
        - conditions: '{{ set_alert_level in alert_group }}'
          sequence:
            - alias: "Send the notification to mobile"
              service: notify.mobile_app_kashyyyk
              data:
                title:  "{{ title }}"
                message: "{{ message }}"
            - alias: "Send the notification to computer"
              service: notify.mobile_app_coruscant
              data:
                title: "{{ title }}"
                message: "{{ message }}"

  notify_angela:
    alias: "Notifications for Angela"
    fields:
      title:
        description: Notification Title
        example: GetawAframe Alert
      message:
        description: Notification Message Body
        example: Motion on front camera
      alert_level: 
        description: 'Level of alertness'
        example: '[Debug|Info|Warn]'
        default: Warn
    variables:
      set_alert_level: '{{ states("input_select.notify_level_angela")}}'
      alert_group: >-
        {% if alert_level == 'Debug' %}
          {{ ('Debug') }}
        {% elif alert_level == 'Info' %}
          {{ ('Debug', 'Info') }}
        {% else %}
          {{ ('Debug', 'Info', 'Warn') }}
        {% endif %}
    sequence:
      - alias: "Check if we should send notification"
        choose:
        - conditions: '{{ set_alert_level in alert_group }}'
          sequence:
            - alias: "Send the notification to mobile"
              service: notify.mobile_app_iphone_58
              data:
                title:  "{{ title }}"
                message: "{{ message }}"

  notify_parents:
    alias: "Notifications for Parents"
    fields:
      title:
        description: Notification Title
        example: GetawAframe Alert
      message:
        description: Notification Message Body
        example: Motion on front camera
      alert_level: 
        description: 'Level of alertness'
        example: '[Debug|Info|Warn]'
        default: Warn
    sequence:
      - alias: "Notify Michael"
        service: script.notify_michael
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          alert_level: "{{ alert_level }}"
      - alias: "Notify Angela"
        service: script.notify_angela
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          alert_level: "{{ alert_level }}"