automation:
  - id: '1605281259031'
    alias: Battery Low Alert
    description: ''
    mode: parallel
    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.lumi_lumi_weather_5aac8205_power
          - sensor.lumi_lumi_weather_64aa8205_power
          - sensor.samjin_multi_0e220d01_power
          - sensor.samjin_multi_cc1d0d01_power
          - sensor.samjin_multi_dd210d01_power
          - sensor.samjin_multi_fcd00d01_power
          - sensor.lumi_lumi_sensor_magnet_aq2_e4a8a902_power
          - sensor.z_wave_plus_thermostat_battery_level
        below: 40
    action:
    - service: notify.persistent_notification
      data:
        title: Battery Low Alert
        message: '{{state_attr(trigger.entity_id, "friendly_name")}} is at {{trigger.to_state.state}}%'