template:
  - binary_sensor:
    - name: Cleared All
      icon: mdi:shield-check-outline
      state: >-
        {{ states("binary_sensor.cleared_doors") == "on" and
           states("binary_sensor.cleared_windows") == "on" and
           states("binary_sensor.cleared_motion") == "on" }}
    - name: Cleared Doors
      icon: mdi:shield-check-outline
      state: >-
        {{ states("lock.touchscreen_deadbolt_z_wave_plus_2") != "unlocked" and 
           states("lock.touchscreen_deadbolt_z_wave_plus") != "unlocked" and
           states("binary_sensor.samjin_multi_fcd00d01_ias_zone") != "on" and
           states("binary_sensor.samjin_multi_0e220d01_ias_zone") != "on" }}
    - name: Cleared Windows
      icon: mdi:shield-check-outline
      state: >-
        {{ states("binary_sensor.samjin_multi_cc1d0d01_ias_zone") != "on" and 
           states("binary_sensor.samjin_multi_dd210d01_ias_zone") != "on" and
           states("binary_sensor.lumi_lumi_sensor_magnet_aq2_e4a8a902_on_off") != "on" and
           states("binary_sensor.lumi_lumi_sensor_magnet_aq2_90dfa102_on_off") != "on" }}
    - name: Cleared Motion
      icon: mdi:shield-check-outline
      state: >-
        {{ states("binary_sensor.4_in_1_sensor_home_security_motion_detection_2") != "on"}}

automation:

  - id: "1605457574856"
    alias: Alarm turn on alerts
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
    action:
      - service: >-
          {% if trigger.to_state.state == 'disarmed' -%} 
            input_boolean.turn_off
          {%- else -%}
            input_boolean.turn_on
          {%- endif %}
        data:
          entity_id: >-
            {% if trigger.to_state.state == 'armed_home' -%}
              input_boolean.notify_on_door_window_events, input_boolean.notify_on_motion_garage
            {%- else -%}
              input_boolean.notify_on_door_window_events, input_boolean.notify_on_motion, input_boolean.notify_on_motion_garage
            {%- endif %}

  - id: "1605533510025"
    alias: Alarm self arm home when disarmed
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.4_in_1_sensor_home_security_motion_detection_2
        from: "on"
        to: "off"
        for: 60
    condition:
      - condition: time
        after: "23:00:00"
        before: "04:00:00"
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: disarmed
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.alarm

  # - id: "1605537922330"
  #   alias: Alarm self disarm when armed home
  #   trigger:
  #     - platform: state
  #       entity_id: 
  #         - binary_sensor.samjin_multi_fcd00d01_ias_zone
  #         - binary_sensor.samjin_multi_0e220d01_ias_zone
  #       from: "off"
  #       to: "on"
  #   condition:
  #     - condition: time
  #       after: "05:00:00"
  #       before: "12:00:00"
  #     - condition: state
  #       entity_id: alarm_control_panel.alarm
  #       state: armed_home
  #     - condition: state
  #       entity_id: input_boolean.guest_mode
  #       state: "off"
  #     # - condition: template
  #     #   value_template: >-
  #     #     {{ 15 < (as_timestamp(utcnow()) - as_timestamp(state_attr("binary_sensor.4_in_1_sensor_home_security_motion_detection_2","last_changed")) }
  #   action:
  #     - service: alarm_control_panel.alarm_disarm
  #       data:
  #         entity_id: 
  #           - alarm_control_panel.alarm
  
  - id: "1617499292370"
    alias: Alarm disarm when doors unlocked
    trigger:
      - platform: state
        entity_id: 
          - lock.touchscreen_deadbolt_z_wave_plus
          - lock.touchscreen_deadbolt_z_wave_plus_2
          - lock.node_15
        from: "locked"
        to: "unlocked"
    condition:
      - alias: "Alarm is armed"
        condition: not
        conditions:
          condition: state
          entity_id: alarm_control_panel.alarm
          state: "disarmed"
    action:
      - alias: "Turn off alarm"
        service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.alarm
          