automation:
  - id: '1608690917908'
    alias: Alarm armed away actions
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: armed_away
    condition: []
    action:
      - service: media_player.media_stop
        data:
          entity_id: media_player.living_room_speaker
      - service: homeassistant.turn_off
        data:
          entity_id: switch.smartthings_outlet_v4_on_off
      
  - id: '1608691373510'
    alias: Alarm disarmed actions
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: disarmed
    condition: []
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.smartthings_outlet_v4_on_off
      - service: homeassistant.turn_off
        data:
          entity_id:
            - input_boolean.heat_away
            - input_boolean.thermostat_hold_temp

script:
  leaving_home_short:
    alias: "Pandemicabin Leaving Home"
    sequence:
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.alarm
  leaving_home_long:
    alias: "Pandemicabin Leaving Home"
    sequence:
      - service: media_player.media_stop
        data:
          entity_id: media_player.living_room_speaker
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.alarm
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.heat_away
  heading_home:
    alias: "Pandemicabin Heading Home"
    sequence:
      - service: climate.set_temperature
        data:
          entity_id: climate.gc_tbz48_battery_powered_z_wave_thermostat_mode
          temperature: >-
            {{ states("input_number.heat_setpoint_away") }}
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.thermostat_hold_temp
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.heat_away