binary_sensor:
  - name: master_ha_api
    platform: rest
    resource: http://100.119.81.44:8122/api/
    device_class: connectivity
    headers:
      Authorization: !secret master_ha_header
      Content-Type: application/json
    value_template: >-
      {{ value_json.message == "API running." }}
  - platform: command_line
    name: AC Power
    command: "cat /sys/class/power_supply/AC/online"
    device_class: connectivity
    payload_on: 1
    payload_off: 0

automation:
  - id: '1608417821607'
    alias: Notify on power state change
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.ac_power
        for: 00:02:00
    condition: []
    action:
      - service: script.notify_conditional
        data:
          recipient: all
          title: 'Pandemicabin Alerts'
          message: >-
            AC power is {{ trigger.to_state.state }}