sensor:
  - platform: imap_email_content
    server: imap.gmail.com
    name: yourporter
    port: 993
    username: !secret google_imap_username
    password: !secret google_imap_password
    folder: GetawAframe
    senders:
      - hello@yourporter.com
      - pfammatter@gmail.com

template:
  - sensor: 
    - name: "Your Porter Listing"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
           regex_replace("=\r\n", "") |
           regex_findall_index("\$listing: (.*?)<br>")}}
    - name: "Your Porter Checkin"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
           regex_replace("=\r\n", "") |
           regex_findall_index("\$inDate: (.*?)<br>")}}
    - name: "Your Porter Checkout"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
           regex_replace("=\r\n", "") |
           regex_findall_index("\$outDate: (.*?)<br>")}}
    - name: "Your Porter Guest Code"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
            regex_findall_index("\$guestCode: (\d{4})")}}

automation:
  - id: d416b9e5-3e87-4ecc-b4c7-eaf18dffcf5c
    alias: Your Porter Guest Code Update
    trigger:
      - platform: state
        entity_id: sensor.your_porter_guest_code
        for: "00:10:00"
    condition:
      - alias: "Listing is GetawAframe"
        condition: state
        entity_id: sensor.your_porter_listing
        state: "GetawAframe"
    action:
      - alias: "Update Guest Code"
        service: input_text.set_value
        target:
          entity_id: input_text.guest_code
        data:
          value: "{{states('sensor.your_porter_guest_code')}}"
