sensor:
  - platform: imap_email_content
    server: imap.gmail.com
    name: yourporter
    port: 993
    username: !secret google_imap_username
    password: !secret google_imap_password
    folder: GetawAframe
    senders:
      - hello@yourporter.com
      - pfammatter@gmail.com

template:
  - sensor: 
    - name: "Your Porter Listing"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
           regex_replace("=\r\n", "") |
           regex_findall_index("\$listing: (.*?)<br>")}}
    - name: "Your Porter Checkin"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
           regex_replace("=\r\n", "") |
           regex_findall_index("\$inDate: (.*?)<br>")}}
    - name: "Your Porter Checkout"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
           regex_replace("=\r\n", "") |
           regex_findall_index("\$outDate: (.*?)<br>")}}
    - name: "Your Porter Guest Code"
      state: >-
        {{ state_attr("sensor.yourporter", "body") |
            regex_findall_index("\$guestCode: (\d{4})")}}
    - name: "Guest Prep Time"
      state: >-
        {{ as_datetime(states('input_datetime.guest_checkin'))
           - timedelta(hours=43, minutes=55) }}

input_datetime:
  guest_checkin:
    name: Guest Checkin
    has_date: true
    has_time: true
  guest_checkout:
    name: Guest Checkout
    has_date: true
    has_time: true

automation:
  - id: d416b9e5-3e87-4ecc-b4c7-eaf18dffcf5c
    alias: Your Porter Guest Code Update
    trigger:
      - platform: state
        entity_id: sensor.your_porter_guest_code
        for: "00:10:00"
    condition:
      - alias: "Listing is GetawAframe"
        condition: state
        entity_id: sensor.your_porter_listing
        state: "GetawAframe"
    action:
      - alias: "Update Guest Code"
        service: input_text.set_value
        target:
          entity_id: input_text.guest_code
        data:
          value: "{{states('sensor.your_porter_guest_code')}}"

  - id: 224608a7-a692-4872-a5f8-2a78865592b1
    alias: Your Porter Checkin Update
    trigger:
      - platform: state
        entity_id: sensor.your_porter_checkin
        for: "00:10:00"
    condition:
      - alias: "Listing is GetawAframe"
        condition: state
        entity_id: sensor.your_porter_listing
        state: "GetawAframe"
    action:
      - alias: "Update guest checkin"
        service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.guest_checkin
        data:
          datetime: >-
            {{strptime(as_datetime(states('sensor.your_porter_checkin')), '')}}

  - id: 22505103-1d83-4bb5-8711-d4bccd54fbff 
    alias: Your Porter Checkout Update
    trigger:
      - platform: state
        entity_id: sensor.your_porter_checkout
        for: "00:10:00"
    condition:
      - alias: "Listing is GetawAframe"
        condition: state
        entity_id: sensor.your_porter_listing
        state: "GetawAframe"
    action:
      - alias: "Update guest checkout"
        service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.guest_checkout
        data:
          datetime: >-
            {{strptime(as_datetime(states('sensor.your_porter_checkout')), '')}}

  - id: f4513555-a729-4f27-9a35-70de349f97a5 
    alias: Prep Reservation
    trigger:
      - platform: time
        at: sensor.guest_prep_time
    condition: []
    action:
      - alias: "Prep reservation turn on"
        service: homeassistant.turn_on
        target:
          entity_id:
            - input_boolean.guest_mode
      - alias: "Prep reservation turn off"
        service: homeassistant.turn_off
        target:
          entity_id:
            - input_boolean.heat_away
      - alias: "Prep reservation notify"
        service: notify.master_ha_notify
        data:
          title: GetawAframe Reservation
          message: Prepping Cabin

  - id: 30d1b55e-a922-4b59-94cd-933cbf59f0c3 
    alias: Begin Reservation
    trigger:
      - platform: time
        at: input_datetime.guest_checkin
    condition: []
    action:
      - alias: "Begin reservation turn on"
        service: homeassistant.turn_on
        target:
          entity_id:
            - input_boolean.guest_code_enable
            - input_boolean.guest_mode
            - input_boolean.thermostat_hold_temp
      - alias: "Begin reservation turn off"
        service: homeassistant.turn_off
        target:
          entity_id:
            - input_boolean.heat_away
      - alias: "Begin reservation notify"
        service: notify.master_ha_notify
        data:
          title: GetawAframe Reservation
          message: Starting reservation

  - id: b4d339dd-7c53-471c-a36e-b2448ac46cd4 
    alias: End Reservation
    trigger:
      - platform: time
        at: input_datetime.guest_checkout
    condition: []
    action:
      - alias: "End reservation turn off"
        service: homeassistant.turn_off
        target:
          entity_id:
            - input_boolean.guest_code_enable
      - alias: "End reservation turn on"
        service: homeassistant.turn_on
        target:
          entity_id:
            - input_boolean.heat_away
      - alias: "End reservation alarm"
        service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.alarm
      - alias: "End reservation notify"
        service: notify.master_ha_notify
        data:
          title: GetawAframe Reservation
          message: Ending reservation